name: Tagr
authentication:
  default_realm: 'friends'
  realms:
    friends:
      credential:
        class: 'Password'
        password_field: 'password'
        password_type: 'clear'
      store:
        class: DBIx::Class
        user_class: TagrDB::Person
        id_field: username
